DELETE http://localhost:3003/api/blogs/6683006b63e23f53f42ffc79
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFuYSIsImlkIjoiNjY4MmVhNjQ0N2QyMTdhMWZhZjJhMmNlIiwiaWF0IjoxNzE5OTE4MTI4LCJleHAiOjE3MTk5MjE3Mjh9.9uNae3_dnHHcPB2Uja1pfPPeSUnZz8IuTJQu02D99q0