DELETE http://localhost:3003/api/blogs/668c38ef614f1db745fb97d4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFuYSIsImlkIjoiNjY4MmVhNjQ0N2QyMTdhMWZhZjJhMmNlIiwiaWF0IjoxNzIwNDY1NjY4LCJleHAiOjE3MjA0NjkyNjh9.Y-N27aYpAIhEnyv7toi0rmkdEcozaGUhESKHEMq