DELETE http://localhost:3003/api/blogs/6683eb7af1b499ef16eaa880
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFuYSIsImlkIjoiNjY4MmVhNjQ0N2QyMTdhMWZhZjJhMmNlIiwiaWF0IjoxNzE5OTI0NDc4LCJleHAiOjE3MTk5MjgwNzh9.GUOHUqMT3YgTVO9w8UhgrXAiDlz-dLV2OekavXPwaRw